services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0 -ui"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 5s
      timeout: 3s
      retries: 10

  users-db:
    image: postgres:13
    container_name: users-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432" # Exposing for local inspection
    volumes:
      - users_data:/var/lib/postgresql/data

  products-db:
    image: postgres:13
    container_name: products-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
    ports:
      - "55433:5432" # Mapping to a different host port
    volumes:
      - products_data:/var/lib/postgresql/data

  users-service:
    build:
      context: .
      dockerfile: services/users-service/Dockerfile
    container_name: users-service
    ports:
      - "50051:50051"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      consul:
        condition: service_healthy
      users-db:
        condition: service_started

  products-service:
    build:
      context: .
      dockerfile: services/products-service/Dockerfile
    container_name: products-service
    ports:
      - "50052:50052"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      consul:
        condition: service_healthy
      products-db:
        condition: service_started

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul
      - users-service
      - products-service

volumes:
  users_data:
  products_data: